name: Anchor Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Anchor
        run: npm install -g @coral-xyz/anchor-cli

      - name: Setup Solana CLI (v1.18.12)
        run: |
          curl -sSfL https://release.solana.com/v1.18.12/install | sh -s
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_ENV
          solana --version

      - name: Decode wallet keypair from secret
        run: |
          mkdir -p ~/.config/solana
          echo "${{ secrets.SOLANA_WALLET }}" | base64 -d > ~/.config/solana/id.json
          chmod 600 ~/.config/solana/id.json

      - name: Anchor Build
        run: anchor build

      - name: Anchor Deploy
        run: anchor deploy
