name: Anchor Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Anchor
        run: npm install -g @coral-xyz/anchor-cli

      - name: Install Solana CLI (from GitHub release)
        run: |
          curl -L https://github.com/solana-labs/solana/releases/download/v1.18.12/solana-release-x86_64-unknown-linux-gnu.tar.bz2 -o solana.tar.bz2
          tar -xjf solana.tar.bz2
          export PATH="$PWD/solana-release/bin:$PATH"
          echo "$PWD/solana-release/bin" >> $GITHUB_PATH
          solana --version

      - name: Decode wallet keypair from secret
        run: |
          mkdir -p ~/.config/solana
          echo "${{ secrets.SOLANA_WALLET }}" | base64 -d > ~/.config/solana/id.json
          chmod 600 ~/.config/solana/id.json

      - name: Anchor Build
        run: anchor build

      - name: Anchor Deploy
        run: anchor deploy
